version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_CONNECTION_URI=sqlite:./data/database.db
      - DIALECT=sqlite
      - TOKEN_SECRET=V3RY_S3CR37_T0K3N
    volumes:
      - backend_data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_data:
